//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------
#pragma warning disable

using System;
using System.Runtime.InteropServices;
using static sokol_gfx;

public static unsafe class sokol_glue
{
    private const string LibraryName = "sokol";

    [DllImport(LibraryName)]
    public static extern sg_context_desc sapp_sgcontext();
}
