//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;

public static unsafe class sokol_app
{
    private const string LibraryName = "sokol";

    public enum sapp_event_type : uint
    {
        SAPP_EVENTTYPE_INVALID = 0U,
        SAPP_EVENTTYPE_KEY_DOWN = 1U,
        SAPP_EVENTTYPE_KEY_UP = 2U,
        SAPP_EVENTTYPE_CHAR = 3U,
        SAPP_EVENTTYPE_MOUSE_DOWN = 4U,
        SAPP_EVENTTYPE_MOUSE_UP = 5U,
        SAPP_EVENTTYPE_MOUSE_SCROLL = 6U,
        SAPP_EVENTTYPE_MOUSE_MOVE = 7U,
        SAPP_EVENTTYPE_MOUSE_ENTER = 8U,
        SAPP_EVENTTYPE_MOUSE_LEAVE = 9U,
        SAPP_EVENTTYPE_TOUCHES_BEGAN = 10U,
        SAPP_EVENTTYPE_TOUCHES_MOVED = 11U,
        SAPP_EVENTTYPE_TOUCHES_ENDED = 12U,
        SAPP_EVENTTYPE_TOUCHES_CANCELLED = 13U,
        SAPP_EVENTTYPE_RESIZED = 14U,
        SAPP_EVENTTYPE_ICONIFIED = 15U,
        SAPP_EVENTTYPE_RESTORED = 16U,
        SAPP_EVENTTYPE_SUSPENDED = 17U,
        SAPP_EVENTTYPE_RESUMED = 18U,
        SAPP_EVENTTYPE_UPDATE_CURSOR = 19U,
        SAPP_EVENTTYPE_QUIT_REQUESTED = 20U,
        SAPP_EVENTTYPE_CLIPBOARD_PASTED = 21U,
        SAPP_EVENTTYPE_FILES_DROPPED = 22U,
        _SAPP_EVENTTYPE_NUM = 23U,
        _SAPP_EVENTTYPE_FORCE_U32 = 2147483647U
    }

    public enum sapp_keycode : uint
    {
        SAPP_KEYCODE_INVALID = 0U,
        SAPP_KEYCODE_SPACE = 32U,
        SAPP_KEYCODE_APOSTROPHE = 39U,
        SAPP_KEYCODE_COMMA = 44U,
        SAPP_KEYCODE_MINUS = 45U,
        SAPP_KEYCODE_PERIOD = 46U,
        SAPP_KEYCODE_SLASH = 47U,
        SAPP_KEYCODE_0 = 48U,
        SAPP_KEYCODE_1 = 49U,
        SAPP_KEYCODE_2 = 50U,
        SAPP_KEYCODE_3 = 51U,
        SAPP_KEYCODE_4 = 52U,
        SAPP_KEYCODE_5 = 53U,
        SAPP_KEYCODE_6 = 54U,
        SAPP_KEYCODE_7 = 55U,
        SAPP_KEYCODE_8 = 56U,
        SAPP_KEYCODE_9 = 57U,
        SAPP_KEYCODE_SEMICOLON = 59U,
        SAPP_KEYCODE_EQUAL = 61U,
        SAPP_KEYCODE_A = 65U,
        SAPP_KEYCODE_B = 66U,
        SAPP_KEYCODE_C = 67U,
        SAPP_KEYCODE_D = 68U,
        SAPP_KEYCODE_E = 69U,
        SAPP_KEYCODE_F = 70U,
        SAPP_KEYCODE_G = 71U,
        SAPP_KEYCODE_H = 72U,
        SAPP_KEYCODE_I = 73U,
        SAPP_KEYCODE_J = 74U,
        SAPP_KEYCODE_K = 75U,
        SAPP_KEYCODE_L = 76U,
        SAPP_KEYCODE_M = 77U,
        SAPP_KEYCODE_N = 78U,
        SAPP_KEYCODE_O = 79U,
        SAPP_KEYCODE_P = 80U,
        SAPP_KEYCODE_Q = 81U,
        SAPP_KEYCODE_R = 82U,
        SAPP_KEYCODE_S = 83U,
        SAPP_KEYCODE_T = 84U,
        SAPP_KEYCODE_U = 85U,
        SAPP_KEYCODE_V = 86U,
        SAPP_KEYCODE_W = 87U,
        SAPP_KEYCODE_X = 88U,
        SAPP_KEYCODE_Y = 89U,
        SAPP_KEYCODE_Z = 90U,
        SAPP_KEYCODE_LEFT_BRACKET = 91U,
        SAPP_KEYCODE_BACKSLASH = 92U,
        SAPP_KEYCODE_RIGHT_BRACKET = 93U,
        SAPP_KEYCODE_GRAVE_ACCENT = 96U,
        SAPP_KEYCODE_WORLD_1 = 161U,
        SAPP_KEYCODE_WORLD_2 = 162U,
        SAPP_KEYCODE_ESCAPE = 256U,
        SAPP_KEYCODE_ENTER = 257U,
        SAPP_KEYCODE_TAB = 258U,
        SAPP_KEYCODE_BACKSPACE = 259U,
        SAPP_KEYCODE_INSERT = 260U,
        SAPP_KEYCODE_DELETE = 261U,
        SAPP_KEYCODE_RIGHT = 262U,
        SAPP_KEYCODE_LEFT = 263U,
        SAPP_KEYCODE_DOWN = 264U,
        SAPP_KEYCODE_UP = 265U,
        SAPP_KEYCODE_PAGE_UP = 266U,
        SAPP_KEYCODE_PAGE_DOWN = 267U,
        SAPP_KEYCODE_HOME = 268U,
        SAPP_KEYCODE_END = 269U,
        SAPP_KEYCODE_CAPS_LOCK = 280U,
        SAPP_KEYCODE_SCROLL_LOCK = 281U,
        SAPP_KEYCODE_NUM_LOCK = 282U,
        SAPP_KEYCODE_PRINT_SCREEN = 283U,
        SAPP_KEYCODE_PAUSE = 284U,
        SAPP_KEYCODE_F1 = 290U,
        SAPP_KEYCODE_F2 = 291U,
        SAPP_KEYCODE_F3 = 292U,
        SAPP_KEYCODE_F4 = 293U,
        SAPP_KEYCODE_F5 = 294U,
        SAPP_KEYCODE_F6 = 295U,
        SAPP_KEYCODE_F7 = 296U,
        SAPP_KEYCODE_F8 = 297U,
        SAPP_KEYCODE_F9 = 298U,
        SAPP_KEYCODE_F10 = 299U,
        SAPP_KEYCODE_F11 = 300U,
        SAPP_KEYCODE_F12 = 301U,
        SAPP_KEYCODE_F13 = 302U,
        SAPP_KEYCODE_F14 = 303U,
        SAPP_KEYCODE_F15 = 304U,
        SAPP_KEYCODE_F16 = 305U,
        SAPP_KEYCODE_F17 = 306U,
        SAPP_KEYCODE_F18 = 307U,
        SAPP_KEYCODE_F19 = 308U,
        SAPP_KEYCODE_F20 = 309U,
        SAPP_KEYCODE_F21 = 310U,
        SAPP_KEYCODE_F22 = 311U,
        SAPP_KEYCODE_F23 = 312U,
        SAPP_KEYCODE_F24 = 313U,
        SAPP_KEYCODE_F25 = 314U,
        SAPP_KEYCODE_KP_0 = 320U,
        SAPP_KEYCODE_KP_1 = 321U,
        SAPP_KEYCODE_KP_2 = 322U,
        SAPP_KEYCODE_KP_3 = 323U,
        SAPP_KEYCODE_KP_4 = 324U,
        SAPP_KEYCODE_KP_5 = 325U,
        SAPP_KEYCODE_KP_6 = 326U,
        SAPP_KEYCODE_KP_7 = 327U,
        SAPP_KEYCODE_KP_8 = 328U,
        SAPP_KEYCODE_KP_9 = 329U,
        SAPP_KEYCODE_KP_DECIMAL = 330U,
        SAPP_KEYCODE_KP_DIVIDE = 331U,
        SAPP_KEYCODE_KP_MULTIPLY = 332U,
        SAPP_KEYCODE_KP_SUBTRACT = 333U,
        SAPP_KEYCODE_KP_ADD = 334U,
        SAPP_KEYCODE_KP_ENTER = 335U,
        SAPP_KEYCODE_KP_EQUAL = 336U,
        SAPP_KEYCODE_LEFT_SHIFT = 340U,
        SAPP_KEYCODE_LEFT_CONTROL = 341U,
        SAPP_KEYCODE_LEFT_ALT = 342U,
        SAPP_KEYCODE_LEFT_SUPER = 343U,
        SAPP_KEYCODE_RIGHT_SHIFT = 344U,
        SAPP_KEYCODE_RIGHT_CONTROL = 345U,
        SAPP_KEYCODE_RIGHT_ALT = 346U,
        SAPP_KEYCODE_RIGHT_SUPER = 347U,
        SAPP_KEYCODE_MENU = 348U
    }

    public enum sapp_mousebutton : uint
    {
        SAPP_MOUSEBUTTON_LEFT = 0U,
        SAPP_MOUSEBUTTON_RIGHT = 1U,
        SAPP_MOUSEBUTTON_MIDDLE = 2U,
        SAPP_MOUSEBUTTON_INVALID = 256U
    }

    public enum sapp_html5_fetch_error : uint
    {
        SAPP_HTML5_FETCH_ERROR_NO_ERROR = 0U,
        SAPP_HTML5_FETCH_ERROR_BUFFER_TOO_SMALL = 1U,
        SAPP_HTML5_FETCH_ERROR_OTHER = 2U
    }

    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct sapp_touchpoint
    {
        [FieldOffset(0)] /* size = 8, padding = 0 */
        public UIntPtr identifier;

        [FieldOffset(8)] /* size = 4, padding = 0 */
        public float pos_x;

        [FieldOffset(12)] /* size = 4, padding = 0 */
        public float pos_y;

        [FieldOffset(16)] /* size = 1, padding = 7 */
        public BlittableBoolean changed;
    }

    [StructLayout(LayoutKind.Explicit, Size = 272, Pack = 8)]
    public struct sapp_event
    {
        [FieldOffset(0)] /* size = 8, padding = 0 */
        public ulong frame_count;

        [FieldOffset(8)] /* size = 4, padding = 0 */
        public sapp_event_type type;

        [FieldOffset(12)] /* size = 4, padding = 0 */
        public sapp_keycode key_code;

        [FieldOffset(16)] /* size = 4, padding = 0 */
        public uint char_code;

        [FieldOffset(20)] /* size = 1, padding = 3 */
        public BlittableBoolean key_repeat;

        [FieldOffset(24)] /* size = 4, padding = 0 */
        public uint modifiers;

        [FieldOffset(28)] /* size = 4, padding = 0 */
        public sapp_mousebutton mouse_button;

        [FieldOffset(32)] /* size = 4, padding = 0 */
        public float mouse_x;

        [FieldOffset(36)] /* size = 4, padding = 0 */
        public float mouse_y;

        [FieldOffset(40)] /* size = 4, padding = 0 */
        public float mouse_dx;

        [FieldOffset(44)] /* size = 4, padding = 0 */
        public float mouse_dy;

        [FieldOffset(48)] /* size = 4, padding = 0 */
        public float scroll_x;

        [FieldOffset(52)] /* size = 4, padding = 0 */
        public float scroll_y;

        [FieldOffset(56)] /* size = 4, padding = 4 */
        public int num_touches;

        [FieldOffset(64)] /* size = 192, padding = 0 */
        public fixed ulong _touches[192 / 8]; /* original type is `sapp_touchpoint [8]` */

        public ref sapp_touchpoint touches(int index = 0)
        {
            fixed (sapp_event* @this = &this)
            {
                var pointer = (sapp_touchpoint* )&@this->_touches[0];
                var pointerOffset = index;
                return ref *(pointer + pointerOffset);
            }
        }

        [FieldOffset(256)] /* size = 4, padding = 0 */
        public int window_width;

        [FieldOffset(260)] /* size = 4, padding = 0 */
        public int window_height;

        [FieldOffset(264)] /* size = 4, padding = 0 */
        public int framebuffer_width;

        [FieldOffset(268)] /* size = 4, padding = 0 */
        public int framebuffer_height;
    }

    [StructLayout(LayoutKind.Explicit, Size = 160, Pack = 8)]
    public struct sapp_desc
    {
        [FieldOffset(0)] /* size = 8, padding = 0 */
        public IntPtr init_cb;

        [FieldOffset(8)] /* size = 8, padding = 0 */
        public IntPtr frame_cb;

        [FieldOffset(16)] /* size = 8, padding = 0 */
        public IntPtr cleanup_cb;

        [FieldOffset(24)] /* size = 8, padding = 0 */
        public IntPtr event_cb;

        [FieldOffset(32)] /* size = 8, padding = 0 */
        public IntPtr fail_cb;

        [FieldOffset(40)] /* size = 8, padding = 0 */
        public void* user_data;

        [FieldOffset(48)] /* size = 8, padding = 0 */
        public IntPtr init_userdata_cb;

        [FieldOffset(56)] /* size = 8, padding = 0 */
        public IntPtr frame_userdata_cb;

        [FieldOffset(64)] /* size = 8, padding = 0 */
        public IntPtr cleanup_userdata_cb;

        [FieldOffset(72)] /* size = 8, padding = 0 */
        public IntPtr event_userdata_cb;

        [FieldOffset(80)] /* size = 8, padding = 0 */
        public IntPtr fail_userdata_cb;

        [FieldOffset(88)] /* size = 4, padding = 0 */
        public int width;

        [FieldOffset(92)] /* size = 4, padding = 0 */
        public int height;

        [FieldOffset(96)] /* size = 4, padding = 0 */
        public int sample_count;

        [FieldOffset(100)] /* size = 4, padding = 0 */
        public int swap_interval;

        [FieldOffset(104)] /* size = 1, padding = 0 */
        public BlittableBoolean high_dpi;

        [FieldOffset(105)] /* size = 1, padding = 0 */
        public BlittableBoolean fullscreen;

        [FieldOffset(106)] /* size = 1, padding = 5 */
        public BlittableBoolean alpha;

        [FieldOffset(112)] /* size = 8, padding = 0 */
        public byte* window_title;

        [FieldOffset(120)] /* size = 1, padding = 0 */
        public BlittableBoolean user_cursor;

        [FieldOffset(121)] /* size = 1, padding = 2 */
        public BlittableBoolean enable_clipboard;

        [FieldOffset(124)] /* size = 4, padding = 0 */
        public int clipboard_size;

        [FieldOffset(128)] /* size = 1, padding = 3 */
        public BlittableBoolean enable_dragndrop;

        [FieldOffset(132)] /* size = 4, padding = 0 */
        public int max_dropped_files;

        [FieldOffset(136)] /* size = 4, padding = 4 */
        public int max_dropped_file_path_length;

        [FieldOffset(144)] /* size = 8, padding = 0 */
        public byte* html5_canvas_name;

        [FieldOffset(152)] /* size = 1, padding = 0 */
        public BlittableBoolean html5_canvas_resize;

        [FieldOffset(153)] /* size = 1, padding = 0 */
        public BlittableBoolean html5_preserve_drawing_buffer;

        [FieldOffset(154)] /* size = 1, padding = 0 */
        public BlittableBoolean html5_premultiplied_alpha;

        [FieldOffset(155)] /* size = 1, padding = 0 */
        public BlittableBoolean html5_ask_leave_site;

        [FieldOffset(156)] /* size = 1, padding = 0 */
        public BlittableBoolean ios_keyboard_resizes_canvas;

        [FieldOffset(157)] /* size = 1, padding = 2 */
        public BlittableBoolean gl_force_gles2;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40, Pack = 8)]
    public struct sapp_html5_fetch_response
    {
        [FieldOffset(0)] /* size = 1, padding = 3 */
        public BlittableBoolean succeeded;

        [FieldOffset(4)] /* size = 4, padding = 0 */
        public sapp_html5_fetch_error error_code;

        [FieldOffset(8)] /* size = 4, padding = 0 */
        public int file_index;

        [FieldOffset(12)] /* size = 4, padding = 0 */
        public uint fetched_size;

        [FieldOffset(16)] /* size = 8, padding = 0 */
        public void* buffer_ptr;

        [FieldOffset(24)] /* size = 4, padding = 4 */
        public uint buffer_size;

        [FieldOffset(32)] /* size = 8, padding = 0 */
        public void* user_data;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40, Pack = 8)]
    public struct sapp_html5_fetch_request
    {
        [FieldOffset(0)] /* size = 4, padding = 4 */
        public int dropped_file_index;

        [FieldOffset(8)] /* size = 8, padding = 0 */
        public IntPtr callback;

        [FieldOffset(16)] /* size = 8, padding = 0 */
        public void* buffer_ptr;

        [FieldOffset(24)] /* size = 4, padding = 4 */
        public uint buffer_size;

        [FieldOffset(32)] /* size = 8, padding = 0 */
        public void* user_data;
    }

    [DllImport(LibraryName)]
    public static extern sapp_desc sokol_main(int argc, byte* argv);

    [DllImport(LibraryName)]
    public static extern BlittableBoolean sapp_isvalid();

    [DllImport(LibraryName)]
    public static extern int sapp_width();

    [DllImport(LibraryName)]
    public static extern int sapp_height();

    [DllImport(LibraryName)]
    public static extern int sapp_color_format();

    [DllImport(LibraryName)]
    public static extern int sapp_depth_format();

    [DllImport(LibraryName)]
    public static extern int sapp_sample_count();

    [DllImport(LibraryName)]
    public static extern BlittableBoolean sapp_high_dpi();

    [DllImport(LibraryName)]
    public static extern float sapp_dpi_scale();

    [DllImport(LibraryName)]
    public static extern void sapp_show_keyboard(BlittableBoolean show);

    [DllImport(LibraryName)]
    public static extern BlittableBoolean sapp_keyboard_shown();

    [DllImport(LibraryName)]
    public static extern BlittableBoolean sapp_is_fullscreen();

    [DllImport(LibraryName)]
    public static extern void sapp_toggle_fullscreen();

    [DllImport(LibraryName)]
    public static extern void sapp_show_mouse(BlittableBoolean show);

    [DllImport(LibraryName)]
    public static extern BlittableBoolean sapp_mouse_shown();

    [DllImport(LibraryName)]
    public static extern void sapp_lock_mouse(BlittableBoolean @lock);

    [DllImport(LibraryName)]
    public static extern BlittableBoolean sapp_mouse_locked();

    [DllImport(LibraryName)]
    public static extern void* sapp_userdata();

    [DllImport(LibraryName)]
    public static extern sapp_desc sapp_query_desc();

    [DllImport(LibraryName)]
    public static extern void sapp_request_quit();

    [DllImport(LibraryName)]
    public static extern void sapp_cancel_quit();

    [DllImport(LibraryName)]
    public static extern void sapp_quit();

    [DllImport(LibraryName)]
    public static extern void sapp_consume_event();

    [DllImport(LibraryName)]
    public static extern ulong sapp_frame_count();

    [DllImport(LibraryName)]
    public static extern void sapp_set_clipboard_string([In] byte* str);

    [DllImport(LibraryName)]
    public static extern byte* sapp_get_clipboard_string();

    [DllImport(LibraryName)]
    public static extern void sapp_set_window_title([In] byte* str);

    [DllImport(LibraryName)]
    public static extern int sapp_get_num_dropped_files();

    [DllImport(LibraryName)]
    public static extern byte* sapp_get_dropped_file_path(int index);

    [DllImport(LibraryName)]
    public static extern void sapp_run([In] sapp_desc* desc);

    [DllImport(LibraryName)]
    public static extern BlittableBoolean sapp_gles2();

    [DllImport(LibraryName)]
    public static extern void sapp_html5_ask_leave_site(BlittableBoolean ask);

    [DllImport(LibraryName)]
    public static extern uint sapp_html5_get_dropped_file_size(int index);

    [DllImport(LibraryName)]
    public static extern void sapp_html5_fetch_dropped_file([In] sapp_html5_fetch_request* request);

    [DllImport(LibraryName)]
    public static extern void* sapp_metal_get_device();

    [DllImport(LibraryName)]
    public static extern void* sapp_metal_get_renderpass_descriptor();

    [DllImport(LibraryName)]
    public static extern void* sapp_metal_get_drawable();

    [DllImport(LibraryName)]
    public static extern void* sapp_macos_get_window();

    [DllImport(LibraryName)]
    public static extern void* sapp_ios_get_window();

    [DllImport(LibraryName)]
    public static extern void* sapp_d3d11_get_device();

    [DllImport(LibraryName)]
    public static extern void* sapp_d3d11_get_device_context();

    [DllImport(LibraryName)]
    public static extern void* sapp_d3d11_get_render_target_view();

    [DllImport(LibraryName)]
    public static extern void* sapp_d3d11_get_depth_stencil_view();

    [DllImport(LibraryName)]
    public static extern void* sapp_win32_get_hwnd();

    [DllImport(LibraryName)]
    public static extern void* sapp_wgpu_get_device();

    [DllImport(LibraryName)]
    public static extern void* sapp_wgpu_get_render_view();

    [DllImport(LibraryName)]
    public static extern void* sapp_wgpu_get_resolve_view();

    [DllImport(LibraryName)]
    public static extern void* sapp_wgpu_get_depth_stencil_view();

    [DllImport(LibraryName)]
    public static extern void* sapp_android_get_native_activity();
}