
//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs (v1.1.0.0)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using C2CS;
using static sokol_gfx;

#nullable enable
#pragma warning disable 1591

public static unsafe partial class sokol_glue
{
    private const string LibraryName = "sokol";

    // Function @ sokol_glue.h:97:37 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_glue.h)
    [DllImport(LibraryName)]
    public static extern sg_context_desc sapp_sgcontext();
}
