
//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs (v1.1.0.0)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using C2CS;

#nullable enable
#pragma warning disable 1591

public static unsafe partial class sokol_fetch
{
    private const string LibraryName = "sokol";

    // Function @ sokol_fetch.h:943:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern void sfetch_continue(sfetch_handle_t h);

    // Function @ sokol_fetch.h:941:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern void sfetch_pause(sfetch_handle_t h);

    // Function @ sokol_fetch.h:939:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern void sfetch_cancel(sfetch_handle_t h);

    // Function @ sokol_fetch.h:937:28 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern void* sfetch_unbind_buffer(sfetch_handle_t h);

    // Function @ sokol_fetch.h:935:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern void sfetch_bind_buffer(sfetch_handle_t h, void* buffer_ptr, uint buffer_size);

    // Function @ sokol_fetch.h:932:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern void sfetch_dowork();

    // Function @ sokol_fetch.h:930:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern CBool sfetch_handle_valid(sfetch_handle_t h);

    // Function @ sokol_fetch.h:928:38 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern sfetch_handle_t sfetch_send(sfetch_request_t* request);

    // Function @ sokol_fetch.h:925:26 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern int sfetch_max_path();

    // Function @ sokol_fetch.h:923:26 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern int sfetch_max_userdata_bytes();

    // Function @ sokol_fetch.h:921:36 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern sfetch_desc_t sfetch_desc();

    // Function @ sokol_fetch.h:919:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern CBool sfetch_valid();

    // Function @ sokol_fetch.h:917:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern void sfetch_shutdown();

    // Function @ sokol_fetch.h:915:27 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [DllImport(LibraryName)]
    public static extern void sfetch_setup(sfetch_desc_t* desc);

    // FunctionPointer @ sokol_fetch.h:898:15 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct sfetch_callback_t
    {
        public delegate* unmanaged<sfetch_response_t*, void> Pointer;
    }

    // Struct @ sokol_fetch.h:864:49 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct sfetch_handle_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uint id;
    }

    // Struct @ sokol_fetch.h:912:3 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [StructLayout(LayoutKind.Explicit, Size = 56, Pack = 8)]
    public struct sfetch_request_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uint _start_canary;

        [FieldOffset(4)] // size = 4, padding = 0
        public uint channel;

        [FieldOffset(8)] // size = 8, padding = 0
        public CString path;

        [FieldOffset(16)] // size = 8, padding = 0
        public sfetch_callback_t callback;

        [FieldOffset(24)] // size = 8, padding = 0
        public void* buffer_ptr;

        [FieldOffset(32)] // size = 4, padding = 0
        public uint buffer_size;

        [FieldOffset(36)] // size = 4, padding = 0
        public uint chunk_size;

        [FieldOffset(40)] // size = 8, padding = 0
        public void* user_data_ptr;

        [FieldOffset(48)] // size = 4, padding = 0
        public uint user_data_size;

        [FieldOffset(52)] // size = 4, padding = 0
        public uint _end_canary;
    }

    // Struct @ sokol_fetch.h:895:3 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [StructLayout(LayoutKind.Explicit, Size = 64, Pack = 8)]
    public struct sfetch_response_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public sfetch_handle_t handle;

        [FieldOffset(4)] // size = 1, padding = 0
        public CBool dispatched;

        [FieldOffset(5)] // size = 1, padding = 0
        public CBool fetched;

        [FieldOffset(6)] // size = 1, padding = 0
        public CBool paused;

        [FieldOffset(7)] // size = 1, padding = 0
        public CBool finished;

        [FieldOffset(8)] // size = 1, padding = 0
        public CBool failed;

        [FieldOffset(9)] // size = 1, padding = 2
        public CBool cancelled;

        [FieldOffset(12)] // size = 4, padding = 0
        public sfetch_error_t error_code;

        [FieldOffset(16)] // size = 4, padding = 0
        public uint channel;

        [FieldOffset(20)] // size = 4, padding = 0
        public uint lane;

        [FieldOffset(24)] // size = 8, padding = 0
        public CString path;

        [FieldOffset(32)] // size = 8, padding = 0
        public void* user_data;

        [FieldOffset(40)] // size = 4, padding = 0
        public uint fetched_offset;

        [FieldOffset(44)] // size = 4, padding = 0
        public uint fetched_size;

        [FieldOffset(48)] // size = 8, padding = 0
        public void* buffer_ptr;

        [FieldOffset(56)] // size = 4, padding = 4
        public uint buffer_size;
    }

    // Struct @ sokol_fetch.h:861:3 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    [StructLayout(LayoutKind.Explicit, Size = 20, Pack = 4)]
    public struct sfetch_desc_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uint _start_canary;

        [FieldOffset(4)] // size = 4, padding = 0
        public uint max_requests;

        [FieldOffset(8)] // size = 4, padding = 0
        public uint num_channels;

        [FieldOffset(12)] // size = 4, padding = 0
        public uint num_lanes;

        [FieldOffset(16)] // size = 4, padding = 0
        public uint _end_canary;
    }

    // Enum @ sokol_fetch.h:875:3 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_fetch.h)
    public enum sfetch_error_t : uint
    {
        SFETCH_ERROR_NO_ERROR = 0U,
        SFETCH_ERROR_FILE_NOT_FOUND = 1U,
        SFETCH_ERROR_NO_BUFFER = 2U,
        SFETCH_ERROR_BUFFER_TOO_SMALL = 3U,
        SFETCH_ERROR_UNEXPECTED_EOF = 4U,
        SFETCH_ERROR_INVALID_HTTP_STATUS = 5U,
        SFETCH_ERROR_CANCELLED = 6U
    }
}
