
//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using C2CS;

#nullable enable
#pragma warning disable 1591

public static unsafe partial class sokol_app
{
    private const string LibraryName = "sokol";
    private static IntPtr _libraryHandle;

    static sokol_app()
    {
        TryLoadApi();
    }

    public static bool TryLoadApi(string? libraryName = LibraryName)
    {
        UnloadApi();
        _libraryHandle = Runtime.LibraryLoad(libraryName!);
        if (_libraryHandle == IntPtr.Zero) return false;
        _LoadVirtualTable();
        return true;
    }

    public static void UnloadApi()
    {
        if (_libraryHandle == IntPtr.Zero) return;
        _UnloadVirtualTable();
        Runtime.LibraryUnload(_libraryHandle);
    }

    // Function @ sokol_app.h:1511:32
    public static void* sapp_android_get_native_activity()
    {
        return _virtualTable.sapp_android_get_native_activity();
    }

    // Function @ sokol_app.h:1508:32
    public static void* sapp_wgpu_get_depth_stencil_view()
    {
        return _virtualTable.sapp_wgpu_get_depth_stencil_view();
    }

    // Function @ sokol_app.h:1506:32
    public static void* sapp_wgpu_get_resolve_view()
    {
        return _virtualTable.sapp_wgpu_get_resolve_view();
    }

    // Function @ sokol_app.h:1504:32
    public static void* sapp_wgpu_get_render_view()
    {
        return _virtualTable.sapp_wgpu_get_render_view();
    }

    // Function @ sokol_app.h:1502:32
    public static void* sapp_wgpu_get_device()
    {
        return _virtualTable.sapp_wgpu_get_device();
    }

    // Function @ sokol_app.h:1499:32
    public static void* sapp_win32_get_hwnd()
    {
        return _virtualTable.sapp_win32_get_hwnd();
    }

    // Function @ sokol_app.h:1497:32
    public static void* sapp_d3d11_get_depth_stencil_view()
    {
        return _virtualTable.sapp_d3d11_get_depth_stencil_view();
    }

    // Function @ sokol_app.h:1495:32
    public static void* sapp_d3d11_get_render_target_view()
    {
        return _virtualTable.sapp_d3d11_get_render_target_view();
    }

    // Function @ sokol_app.h:1493:32
    public static void* sapp_d3d11_get_swap_chain()
    {
        return _virtualTable.sapp_d3d11_get_swap_chain();
    }

    // Function @ sokol_app.h:1491:32
    public static void* sapp_d3d11_get_device_context()
    {
        return _virtualTable.sapp_d3d11_get_device_context();
    }

    // Function @ sokol_app.h:1489:32
    public static void* sapp_d3d11_get_device()
    {
        return _virtualTable.sapp_d3d11_get_device();
    }

    // Function @ sokol_app.h:1486:32
    public static void* sapp_ios_get_window()
    {
        return _virtualTable.sapp_ios_get_window();
    }

    // Function @ sokol_app.h:1484:32
    public static void* sapp_macos_get_window()
    {
        return _virtualTable.sapp_macos_get_window();
    }

    // Function @ sokol_app.h:1482:32
    public static void* sapp_metal_get_drawable()
    {
        return _virtualTable.sapp_metal_get_drawable();
    }

    // Function @ sokol_app.h:1480:32
    public static void* sapp_metal_get_renderpass_descriptor()
    {
        return _virtualTable.sapp_metal_get_renderpass_descriptor();
    }

    // Function @ sokol_app.h:1478:32
    public static void* sapp_metal_get_device()
    {
        return _virtualTable.sapp_metal_get_device();
    }

    // Function @ sokol_app.h:1475:25
    public static void sapp_html5_fetch_dropped_file(sapp_html5_fetch_request* request)
    {
        _virtualTable.sapp_html5_fetch_dropped_file(request);
    }

    // Function @ sokol_app.h:1473:29
    public static uint sapp_html5_get_dropped_file_size(int index)
    {
        return _virtualTable.sapp_html5_get_dropped_file_size(index);
    }

    // Function @ sokol_app.h:1471:25
    public static void sapp_html5_ask_leave_site(CBool ask)
    {
        _virtualTable.sapp_html5_ask_leave_site(ask);
    }

    // Function @ sokol_app.h:1468:25
    public static CBool sapp_gles2()
    {
        return _virtualTable.sapp_gles2();
    }

    // Function @ sokol_app.h:1465:25
    public static void sapp_run(sapp_desc* desc)
    {
        _virtualTable.sapp_run(desc);
    }

    // Function @ sokol_app.h:1462:32
    public static CString sapp_get_dropped_file_path(int index)
    {
        return _virtualTable.sapp_get_dropped_file_path(index);
    }

    // Function @ sokol_app.h:1460:24
    public static int sapp_get_num_dropped_files()
    {
        return _virtualTable.sapp_get_num_dropped_files();
    }

    // Function @ sokol_app.h:1458:25
    public static void sapp_set_icon(sapp_icon_desc* icon_desc)
    {
        _virtualTable.sapp_set_icon(icon_desc);
    }

    // Function @ sokol_app.h:1456:25
    public static void sapp_set_window_title(CString str)
    {
        _virtualTable.sapp_set_window_title(str);
    }

    // Function @ sokol_app.h:1454:32
    public static CString sapp_get_clipboard_string()
    {
        return _virtualTable.sapp_get_clipboard_string();
    }

    // Function @ sokol_app.h:1452:25
    public static void sapp_set_clipboard_string(CString str)
    {
        _virtualTable.sapp_set_clipboard_string(str);
    }

    // Function @ sokol_app.h:1450:29
    public static ulong sapp_frame_count()
    {
        return _virtualTable.sapp_frame_count();
    }

    // Function @ sokol_app.h:1448:25
    public static void sapp_consume_event()
    {
        _virtualTable.sapp_consume_event();
    }

    // Function @ sokol_app.h:1446:25
    public static void sapp_quit()
    {
        _virtualTable.sapp_quit();
    }

    // Function @ sokol_app.h:1444:25
    public static void sapp_cancel_quit()
    {
        _virtualTable.sapp_cancel_quit();
    }

    // Function @ sokol_app.h:1442:25
    public static void sapp_request_quit()
    {
        _virtualTable.sapp_request_quit();
    }

    // Function @ sokol_app.h:1440:30
    public static sapp_desc sapp_query_desc()
    {
        return _virtualTable.sapp_query_desc();
    }

    // Function @ sokol_app.h:1438:26
    public static void* sapp_userdata()
    {
        return _virtualTable.sapp_userdata();
    }

    // Function @ sokol_app.h:1436:25
    public static CBool sapp_mouse_locked()
    {
        return _virtualTable.sapp_mouse_locked();
    }

    // Function @ sokol_app.h:1434:25
    public static void sapp_lock_mouse(CBool @lock)
    {
        _virtualTable.sapp_lock_mouse(@lock);
    }

    // Function @ sokol_app.h:1432:25
    public static CBool sapp_mouse_shown()
    {
        return _virtualTable.sapp_mouse_shown();
    }

    // Function @ sokol_app.h:1430:25
    public static void sapp_show_mouse(CBool show)
    {
        _virtualTable.sapp_show_mouse(show);
    }

    // Function @ sokol_app.h:1428:25
    public static void sapp_toggle_fullscreen()
    {
        _virtualTable.sapp_toggle_fullscreen();
    }

    // Function @ sokol_app.h:1426:25
    public static CBool sapp_is_fullscreen()
    {
        return _virtualTable.sapp_is_fullscreen();
    }

    // Function @ sokol_app.h:1424:25
    public static CBool sapp_keyboard_shown()
    {
        return _virtualTable.sapp_keyboard_shown();
    }

    // Function @ sokol_app.h:1422:25
    public static void sapp_show_keyboard(CBool show)
    {
        _virtualTable.sapp_show_keyboard(show);
    }

    // Function @ sokol_app.h:1420:26
    public static float sapp_dpi_scale()
    {
        return _virtualTable.sapp_dpi_scale();
    }

    // Function @ sokol_app.h:1418:25
    public static CBool sapp_high_dpi()
    {
        return _virtualTable.sapp_high_dpi();
    }

    // Function @ sokol_app.h:1416:24
    public static int sapp_sample_count()
    {
        return _virtualTable.sapp_sample_count();
    }

    // Function @ sokol_app.h:1414:24
    public static int sapp_depth_format()
    {
        return _virtualTable.sapp_depth_format();
    }

    // Function @ sokol_app.h:1412:24
    public static int sapp_color_format()
    {
        return _virtualTable.sapp_color_format();
    }

    // Function @ sokol_app.h:1410:26
    public static float sapp_heightf()
    {
        return _virtualTable.sapp_heightf();
    }

    // Function @ sokol_app.h:1408:24
    public static int sapp_height()
    {
        return _virtualTable.sapp_height();
    }

    // Function @ sokol_app.h:1406:26
    public static float sapp_widthf()
    {
        return _virtualTable.sapp_widthf();
    }

    // Function @ sokol_app.h:1404:24
    public static int sapp_width()
    {
        return _virtualTable.sapp_width();
    }

    // Function @ sokol_app.h:1402:25
    public static CBool sapp_isvalid()
    {
        return _virtualTable.sapp_isvalid();
    }

    // Function @ sokol_app.h:1399:18
    public static sapp_desc sokol_main(int argc, CString* argv)
    {
        return _virtualTable.sokol_main(argc, argv);
    }

    // FunctionPointer @ sokol_app.h:1392:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_APP_Sapp_html5_fetch_responsePtr_Void
    {
        public delegate* unmanaged<sapp_html5_fetch_response*, void> Pointer;
    }

    // FunctionPointer @ sokol_app.h:1340:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_APP_CString_VoidPtr_Void
    {
        public delegate* unmanaged<CString, void*, void> Pointer;
    }

    // FunctionPointer @ sokol_app.h:1339:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_APP_Sapp_eventPtr_VoidPtr_Void
    {
        public delegate* unmanaged<sapp_event*, void*, void> Pointer;
    }

    // FunctionPointer @ sokol_app.h:1336:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_APP_VoidPtr_Void
    {
        public delegate* unmanaged<void*, void> Pointer;
    }

    // FunctionPointer @ sokol_app.h:1333:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_APP_CString_Void
    {
        public delegate* unmanaged<CString, void> Pointer;
    }

    // FunctionPointer @ sokol_app.h:1332:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_APP_Sapp_eventPtr_Void
    {
        public delegate* unmanaged<sapp_event*, void> Pointer;
    }

    // FunctionPointer @ sokol_app.h:1329:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_APP_Void
    {
        public delegate* unmanaged<void> Pointer;
    }

    // Struct @ sokol_app.h:1396:3
    [StructLayout(LayoutKind.Explicit, Size = 40, Pack = 8)]
    public struct sapp_html5_fetch_request
    {
        [FieldOffset(0)] // size = 4, padding = 4
        public int dropped_file_index;

        [FieldOffset(8)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_Sapp_html5_fetch_responsePtr_Void callback;

        [FieldOffset(16)] // size = 8, padding = 0
        public void* buffer_ptr;

        [FieldOffset(24)] // size = 4, padding = 4
        public uint buffer_size;

        [FieldOffset(32)] // size = 8, padding = 0
        public void* user_data;
    }

    // Struct @ sokol_app.h:1388:3
    [StructLayout(LayoutKind.Explicit, Size = 40, Pack = 8)]
    public struct sapp_html5_fetch_response
    {
        [FieldOffset(0)] // size = 1, padding = 3
        public CBool succeeded;

        [FieldOffset(4)] // size = 4, padding = 0
        public sapp_html5_fetch_error error_code;

        [FieldOffset(8)] // size = 4, padding = 0
        public int file_index;

        [FieldOffset(12)] // size = 4, padding = 0
        public uint fetched_size;

        [FieldOffset(16)] // size = 8, padding = 0
        public void* buffer_ptr;

        [FieldOffset(24)] // size = 4, padding = 4
        public uint buffer_size;

        [FieldOffset(32)] // size = 8, padding = 0
        public void* user_data;
    }

    // Struct @ sokol_app.h:1369:3
    [StructLayout(LayoutKind.Explicit, Size = 368, Pack = 8)]
    public struct sapp_desc
    {
        [FieldOffset(0)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_Void init_cb;

        [FieldOffset(8)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_Void frame_cb;

        [FieldOffset(16)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_Void cleanup_cb;

        [FieldOffset(24)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_Sapp_eventPtr_Void event_cb;

        [FieldOffset(32)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_CString_Void fail_cb;

        [FieldOffset(40)] // size = 8, padding = 0
        public void* user_data;

        [FieldOffset(48)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_VoidPtr_Void init_userdata_cb;

        [FieldOffset(56)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_VoidPtr_Void frame_userdata_cb;

        [FieldOffset(64)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_VoidPtr_Void cleanup_userdata_cb;

        [FieldOffset(72)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_Sapp_eventPtr_VoidPtr_Void event_userdata_cb;

        [FieldOffset(80)] // size = 8, padding = 0
        public FnPtr_SOKOL_APP_CString_VoidPtr_Void fail_userdata_cb;

        [FieldOffset(88)] // size = 4, padding = 0
        public int width;

        [FieldOffset(92)] // size = 4, padding = 0
        public int height;

        [FieldOffset(96)] // size = 4, padding = 0
        public int sample_count;

        [FieldOffset(100)] // size = 4, padding = 0
        public int swap_interval;

        [FieldOffset(104)] // size = 1, padding = 0
        public CBool high_dpi;

        [FieldOffset(105)] // size = 1, padding = 0
        public CBool fullscreen;

        [FieldOffset(106)] // size = 1, padding = 5
        public CBool alpha;

        [FieldOffset(112)] // size = 8, padding = 0
        public CString window_title;

        [FieldOffset(120)] // size = 1, padding = 0
        public CBool user_cursor;

        [FieldOffset(121)] // size = 1, padding = 2
        public CBool enable_clipboard;

        [FieldOffset(124)] // size = 4, padding = 0
        public int clipboard_size;

        [FieldOffset(128)] // size = 1, padding = 3
        public CBool enable_dragndrop;

        [FieldOffset(132)] // size = 4, padding = 0
        public int max_dropped_files;

        [FieldOffset(136)] // size = 4, padding = 4
        public int max_dropped_file_path_length;

        [FieldOffset(144)] // size = 200, padding = 0
        public sapp_icon_desc icon;

        [FieldOffset(344)] // size = 1, padding = 0
        public CBool gl_force_gles2;

        [FieldOffset(345)] // size = 1, padding = 0
        public CBool win32_console_utf8;

        [FieldOffset(346)] // size = 1, padding = 0
        public CBool win32_console_create;

        [FieldOffset(347)] // size = 1, padding = 4
        public CBool win32_console_attach;

        [FieldOffset(352)] // size = 8, padding = 0
        public CString html5_canvas_name;

        [FieldOffset(360)] // size = 1, padding = 0
        public CBool html5_canvas_resize;

        [FieldOffset(361)] // size = 1, padding = 0
        public CBool html5_preserve_drawing_buffer;

        [FieldOffset(362)] // size = 1, padding = 0
        public CBool html5_premultiplied_alpha;

        [FieldOffset(363)] // size = 1, padding = 0
        public CBool html5_ask_leave_site;

        [FieldOffset(364)] // size = 1, padding = 3
        public CBool ios_keyboard_resizes_canvas;
    }

    // Struct @ sokol_app.h:1325:3
    [StructLayout(LayoutKind.Explicit, Size = 200, Pack = 8)]
    public struct sapp_icon_desc
    {
        [FieldOffset(0)] // size = 1, padding = 7
        public CBool sokol_default;

        [FieldOffset(8)] // size = 192, padding = 0
        public fixed ulong _images[192 / 8]; // sapp_image_desc[8]

        public Span<sapp_image_desc> images
        {
            get
            {
                fixed (sapp_icon_desc* @this = &this)
                {
                    var pointer = &@this->_images[0];
                    var span = new Span<sapp_image_desc>(pointer, 8);
                    return span;
                }
            }
        }
    }

    // Struct @ sokol_app.h:1302:3
    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct sapp_image_desc
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int width;

        [FieldOffset(4)] // size = 4, padding = 0
        public int height;

        [FieldOffset(8)] // size = 16, padding = 0
        public sapp_range pixels;
    }

    // Struct @ sokol_app.h:1275:3
    [StructLayout(LayoutKind.Explicit, Size = 16, Pack = 8)]
    public struct sapp_range
    {
        [FieldOffset(0)] // size = 8, padding = 0
        public void* ptr;

        [FieldOffset(8)] // size = 8, padding = 0
        public ulong size;
    }

    // Struct @ sokol_app.h:1264:3
    [StructLayout(LayoutKind.Explicit, Size = 272, Pack = 8)]
    public struct sapp_event
    {
        [FieldOffset(0)] // size = 8, padding = 0
        public ulong frame_count;

        [FieldOffset(8)] // size = 4, padding = 0
        public sapp_event_type type;

        [FieldOffset(12)] // size = 4, padding = 0
        public sapp_keycode key_code;

        [FieldOffset(16)] // size = 4, padding = 0
        public uint char_code;

        [FieldOffset(20)] // size = 1, padding = 3
        public CBool key_repeat;

        [FieldOffset(24)] // size = 4, padding = 0
        public uint modifiers;

        [FieldOffset(28)] // size = 4, padding = 0
        public sapp_mousebutton mouse_button;

        [FieldOffset(32)] // size = 4, padding = 0
        public float mouse_x;

        [FieldOffset(36)] // size = 4, padding = 0
        public float mouse_y;

        [FieldOffset(40)] // size = 4, padding = 0
        public float mouse_dx;

        [FieldOffset(44)] // size = 4, padding = 0
        public float mouse_dy;

        [FieldOffset(48)] // size = 4, padding = 0
        public float scroll_x;

        [FieldOffset(52)] // size = 4, padding = 0
        public float scroll_y;

        [FieldOffset(56)] // size = 4, padding = 4
        public int num_touches;

        [FieldOffset(64)] // size = 192, padding = 0
        public fixed ulong _touches[192 / 8]; // sapp_touchpoint[8]

        public Span<sapp_touchpoint> touches
        {
            get
            {
                fixed (sapp_event* @this = &this)
                {
                    var pointer = &@this->_touches[0];
                    var span = new Span<sapp_touchpoint>(pointer, 8);
                    return span;
                }
            }
        }

        [FieldOffset(256)] // size = 4, padding = 0
        public int window_width;

        [FieldOffset(260)] // size = 4, padding = 0
        public int window_height;

        [FieldOffset(264)] // size = 4, padding = 0
        public int framebuffer_width;

        [FieldOffset(268)] // size = 4, padding = 0
        public int framebuffer_height;
    }

    // Struct @ sokol_app.h:1206:3
    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct sapp_touchpoint
    {
        [FieldOffset(0)] // size = 8, padding = 0
        public UIntPtr identifier;

        [FieldOffset(8)] // size = 4, padding = 0
        public float pos_x;

        [FieldOffset(12)] // size = 4, padding = 0
        public float pos_y;

        [FieldOffset(16)] // size = 1, padding = 7
        public CBool changed;
    }

    // Enum @ sokol_app.h:1378:3
    public enum sapp_html5_fetch_error : uint
    {
        SAPP_HTML5_FETCH_ERROR_NO_ERROR = 0U,
        SAPP_HTML5_FETCH_ERROR_BUFFER_TOO_SMALL = 1U,
        SAPP_HTML5_FETCH_ERROR_OTHER = 2U
    }

    // Enum @ sokol_app.h:1219:3
    public enum sapp_mousebutton : uint
    {
        SAPP_MOUSEBUTTON_LEFT = 0U,
        SAPP_MOUSEBUTTON_RIGHT = 1U,
        SAPP_MOUSEBUTTON_MIDDLE = 2U,
        SAPP_MOUSEBUTTON_INVALID = 256U
    }

    // Enum @ sokol_app.h:1190:3
    public enum sapp_keycode : uint
    {
        SAPP_KEYCODE_INVALID = 0U,
        SAPP_KEYCODE_SPACE = 32U,
        SAPP_KEYCODE_APOSTROPHE = 39U,
        SAPP_KEYCODE_COMMA = 44U,
        SAPP_KEYCODE_MINUS = 45U,
        SAPP_KEYCODE_PERIOD = 46U,
        SAPP_KEYCODE_SLASH = 47U,
        SAPP_KEYCODE_0 = 48U,
        SAPP_KEYCODE_1 = 49U,
        SAPP_KEYCODE_2 = 50U,
        SAPP_KEYCODE_3 = 51U,
        SAPP_KEYCODE_4 = 52U,
        SAPP_KEYCODE_5 = 53U,
        SAPP_KEYCODE_6 = 54U,
        SAPP_KEYCODE_7 = 55U,
        SAPP_KEYCODE_8 = 56U,
        SAPP_KEYCODE_9 = 57U,
        SAPP_KEYCODE_SEMICOLON = 59U,
        SAPP_KEYCODE_EQUAL = 61U,
        SAPP_KEYCODE_A = 65U,
        SAPP_KEYCODE_B = 66U,
        SAPP_KEYCODE_C = 67U,
        SAPP_KEYCODE_D = 68U,
        SAPP_KEYCODE_E = 69U,
        SAPP_KEYCODE_F = 70U,
        SAPP_KEYCODE_G = 71U,
        SAPP_KEYCODE_H = 72U,
        SAPP_KEYCODE_I = 73U,
        SAPP_KEYCODE_J = 74U,
        SAPP_KEYCODE_K = 75U,
        SAPP_KEYCODE_L = 76U,
        SAPP_KEYCODE_M = 77U,
        SAPP_KEYCODE_N = 78U,
        SAPP_KEYCODE_O = 79U,
        SAPP_KEYCODE_P = 80U,
        SAPP_KEYCODE_Q = 81U,
        SAPP_KEYCODE_R = 82U,
        SAPP_KEYCODE_S = 83U,
        SAPP_KEYCODE_T = 84U,
        SAPP_KEYCODE_U = 85U,
        SAPP_KEYCODE_V = 86U,
        SAPP_KEYCODE_W = 87U,
        SAPP_KEYCODE_X = 88U,
        SAPP_KEYCODE_Y = 89U,
        SAPP_KEYCODE_Z = 90U,
        SAPP_KEYCODE_LEFT_BRACKET = 91U,
        SAPP_KEYCODE_BACKSLASH = 92U,
        SAPP_KEYCODE_RIGHT_BRACKET = 93U,
        SAPP_KEYCODE_GRAVE_ACCENT = 96U,
        SAPP_KEYCODE_WORLD_1 = 161U,
        SAPP_KEYCODE_WORLD_2 = 162U,
        SAPP_KEYCODE_ESCAPE = 256U,
        SAPP_KEYCODE_ENTER = 257U,
        SAPP_KEYCODE_TAB = 258U,
        SAPP_KEYCODE_BACKSPACE = 259U,
        SAPP_KEYCODE_INSERT = 260U,
        SAPP_KEYCODE_DELETE = 261U,
        SAPP_KEYCODE_RIGHT = 262U,
        SAPP_KEYCODE_LEFT = 263U,
        SAPP_KEYCODE_DOWN = 264U,
        SAPP_KEYCODE_UP = 265U,
        SAPP_KEYCODE_PAGE_UP = 266U,
        SAPP_KEYCODE_PAGE_DOWN = 267U,
        SAPP_KEYCODE_HOME = 268U,
        SAPP_KEYCODE_END = 269U,
        SAPP_KEYCODE_CAPS_LOCK = 280U,
        SAPP_KEYCODE_SCROLL_LOCK = 281U,
        SAPP_KEYCODE_NUM_LOCK = 282U,
        SAPP_KEYCODE_PRINT_SCREEN = 283U,
        SAPP_KEYCODE_PAUSE = 284U,
        SAPP_KEYCODE_F1 = 290U,
        SAPP_KEYCODE_F2 = 291U,
        SAPP_KEYCODE_F3 = 292U,
        SAPP_KEYCODE_F4 = 293U,
        SAPP_KEYCODE_F5 = 294U,
        SAPP_KEYCODE_F6 = 295U,
        SAPP_KEYCODE_F7 = 296U,
        SAPP_KEYCODE_F8 = 297U,
        SAPP_KEYCODE_F9 = 298U,
        SAPP_KEYCODE_F10 = 299U,
        SAPP_KEYCODE_F11 = 300U,
        SAPP_KEYCODE_F12 = 301U,
        SAPP_KEYCODE_F13 = 302U,
        SAPP_KEYCODE_F14 = 303U,
        SAPP_KEYCODE_F15 = 304U,
        SAPP_KEYCODE_F16 = 305U,
        SAPP_KEYCODE_F17 = 306U,
        SAPP_KEYCODE_F18 = 307U,
        SAPP_KEYCODE_F19 = 308U,
        SAPP_KEYCODE_F20 = 309U,
        SAPP_KEYCODE_F21 = 310U,
        SAPP_KEYCODE_F22 = 311U,
        SAPP_KEYCODE_F23 = 312U,
        SAPP_KEYCODE_F24 = 313U,
        SAPP_KEYCODE_F25 = 314U,
        SAPP_KEYCODE_KP_0 = 320U,
        SAPP_KEYCODE_KP_1 = 321U,
        SAPP_KEYCODE_KP_2 = 322U,
        SAPP_KEYCODE_KP_3 = 323U,
        SAPP_KEYCODE_KP_4 = 324U,
        SAPP_KEYCODE_KP_5 = 325U,
        SAPP_KEYCODE_KP_6 = 326U,
        SAPP_KEYCODE_KP_7 = 327U,
        SAPP_KEYCODE_KP_8 = 328U,
        SAPP_KEYCODE_KP_9 = 329U,
        SAPP_KEYCODE_KP_DECIMAL = 330U,
        SAPP_KEYCODE_KP_DIVIDE = 331U,
        SAPP_KEYCODE_KP_MULTIPLY = 332U,
        SAPP_KEYCODE_KP_SUBTRACT = 333U,
        SAPP_KEYCODE_KP_ADD = 334U,
        SAPP_KEYCODE_KP_ENTER = 335U,
        SAPP_KEYCODE_KP_EQUAL = 336U,
        SAPP_KEYCODE_LEFT_SHIFT = 340U,
        SAPP_KEYCODE_LEFT_CONTROL = 341U,
        SAPP_KEYCODE_LEFT_ALT = 342U,
        SAPP_KEYCODE_LEFT_SUPER = 343U,
        SAPP_KEYCODE_RIGHT_SHIFT = 344U,
        SAPP_KEYCODE_RIGHT_CONTROL = 345U,
        SAPP_KEYCODE_RIGHT_ALT = 346U,
        SAPP_KEYCODE_RIGHT_SUPER = 347U,
        SAPP_KEYCODE_MENU = 348U
    }

    // Enum @ sokol_app.h:1058:3
    public enum sapp_event_type : uint
    {
        SAPP_EVENTTYPE_INVALID = 0U,
        SAPP_EVENTTYPE_KEY_DOWN = 1U,
        SAPP_EVENTTYPE_KEY_UP = 2U,
        SAPP_EVENTTYPE_CHAR = 3U,
        SAPP_EVENTTYPE_MOUSE_DOWN = 4U,
        SAPP_EVENTTYPE_MOUSE_UP = 5U,
        SAPP_EVENTTYPE_MOUSE_SCROLL = 6U,
        SAPP_EVENTTYPE_MOUSE_MOVE = 7U,
        SAPP_EVENTTYPE_MOUSE_ENTER = 8U,
        SAPP_EVENTTYPE_MOUSE_LEAVE = 9U,
        SAPP_EVENTTYPE_TOUCHES_BEGAN = 10U,
        SAPP_EVENTTYPE_TOUCHES_MOVED = 11U,
        SAPP_EVENTTYPE_TOUCHES_ENDED = 12U,
        SAPP_EVENTTYPE_TOUCHES_CANCELLED = 13U,
        SAPP_EVENTTYPE_RESIZED = 14U,
        SAPP_EVENTTYPE_ICONIFIED = 15U,
        SAPP_EVENTTYPE_RESTORED = 16U,
        SAPP_EVENTTYPE_SUSPENDED = 17U,
        SAPP_EVENTTYPE_RESUMED = 18U,
        SAPP_EVENTTYPE_UPDATE_CURSOR = 19U,
        SAPP_EVENTTYPE_QUIT_REQUESTED = 20U,
        SAPP_EVENTTYPE_CLIPBOARD_PASTED = 21U,
        SAPP_EVENTTYPE_FILES_DROPPED = 22U,
        _SAPP_EVENTTYPE_NUM = 23U,
        _SAPP_EVENTTYPE_FORCE_U32 = 2147483647U
    }

    private static void _LoadVirtualTable()
    {
        #region "Functions"
        _virtualTable.sapp_android_get_native_activity = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_android_get_native_activity");
        _virtualTable.sapp_wgpu_get_depth_stencil_view = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_wgpu_get_depth_stencil_view");
        _virtualTable.sapp_wgpu_get_resolve_view = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_wgpu_get_resolve_view");
        _virtualTable.sapp_wgpu_get_render_view = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_wgpu_get_render_view");
        _virtualTable.sapp_wgpu_get_device = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_wgpu_get_device");
        _virtualTable.sapp_win32_get_hwnd = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_win32_get_hwnd");
        _virtualTable.sapp_d3d11_get_depth_stencil_view = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_d3d11_get_depth_stencil_view");
        _virtualTable.sapp_d3d11_get_render_target_view = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_d3d11_get_render_target_view");
        _virtualTable.sapp_d3d11_get_swap_chain = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_d3d11_get_swap_chain");
        _virtualTable.sapp_d3d11_get_device_context = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_d3d11_get_device_context");
        _virtualTable.sapp_d3d11_get_device = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_d3d11_get_device");
        _virtualTable.sapp_ios_get_window = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_ios_get_window");
        _virtualTable.sapp_macos_get_window = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_macos_get_window");
        _virtualTable.sapp_metal_get_drawable = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_metal_get_drawable");
        _virtualTable.sapp_metal_get_renderpass_descriptor = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_metal_get_renderpass_descriptor");
        _virtualTable.sapp_metal_get_device = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_metal_get_device");
        _virtualTable.sapp_html5_fetch_dropped_file = (delegate* unmanaged[Cdecl]<sapp_html5_fetch_request*, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_html5_fetch_dropped_file");
        _virtualTable.sapp_html5_get_dropped_file_size = (delegate* unmanaged[Cdecl]<int, uint>)Runtime.LibraryGetExport(_libraryHandle, "sapp_html5_get_dropped_file_size");
        _virtualTable.sapp_html5_ask_leave_site = (delegate* unmanaged[Cdecl]<CBool, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_html5_ask_leave_site");
        _virtualTable.sapp_gles2 = (delegate* unmanaged[Cdecl]<CBool>)Runtime.LibraryGetExport(_libraryHandle, "sapp_gles2");
        _virtualTable.sapp_run = (delegate* unmanaged[Cdecl]<sapp_desc*, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_run");
        _virtualTable.sapp_get_dropped_file_path = (delegate* unmanaged[Cdecl]<int, CString>)Runtime.LibraryGetExport(_libraryHandle, "sapp_get_dropped_file_path");
        _virtualTable.sapp_get_num_dropped_files = (delegate* unmanaged[Cdecl]<int>)Runtime.LibraryGetExport(_libraryHandle, "sapp_get_num_dropped_files");
        _virtualTable.sapp_set_icon = (delegate* unmanaged[Cdecl]<sapp_icon_desc*, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_set_icon");
        _virtualTable.sapp_set_window_title = (delegate* unmanaged[Cdecl]<CString, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_set_window_title");
        _virtualTable.sapp_get_clipboard_string = (delegate* unmanaged[Cdecl]<CString>)Runtime.LibraryGetExport(_libraryHandle, "sapp_get_clipboard_string");
        _virtualTable.sapp_set_clipboard_string = (delegate* unmanaged[Cdecl]<CString, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_set_clipboard_string");
        _virtualTable.sapp_frame_count = (delegate* unmanaged[Cdecl]<ulong>)Runtime.LibraryGetExport(_libraryHandle, "sapp_frame_count");
        _virtualTable.sapp_consume_event = (delegate* unmanaged[Cdecl]<void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_consume_event");
        _virtualTable.sapp_quit = (delegate* unmanaged[Cdecl]<void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_quit");
        _virtualTable.sapp_cancel_quit = (delegate* unmanaged[Cdecl]<void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_cancel_quit");
        _virtualTable.sapp_request_quit = (delegate* unmanaged[Cdecl]<void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_request_quit");
        _virtualTable.sapp_query_desc = (delegate* unmanaged[Cdecl]<sapp_desc>)Runtime.LibraryGetExport(_libraryHandle, "sapp_query_desc");
        _virtualTable.sapp_userdata = (delegate* unmanaged[Cdecl]<void*>)Runtime.LibraryGetExport(_libraryHandle, "sapp_userdata");
        _virtualTable.sapp_mouse_locked = (delegate* unmanaged[Cdecl]<CBool>)Runtime.LibraryGetExport(_libraryHandle, "sapp_mouse_locked");
        _virtualTable.sapp_lock_mouse = (delegate* unmanaged[Cdecl]<CBool, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_lock_mouse");
        _virtualTable.sapp_mouse_shown = (delegate* unmanaged[Cdecl]<CBool>)Runtime.LibraryGetExport(_libraryHandle, "sapp_mouse_shown");
        _virtualTable.sapp_show_mouse = (delegate* unmanaged[Cdecl]<CBool, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_show_mouse");
        _virtualTable.sapp_toggle_fullscreen = (delegate* unmanaged[Cdecl]<void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_toggle_fullscreen");
        _virtualTable.sapp_is_fullscreen = (delegate* unmanaged[Cdecl]<CBool>)Runtime.LibraryGetExport(_libraryHandle, "sapp_is_fullscreen");
        _virtualTable.sapp_keyboard_shown = (delegate* unmanaged[Cdecl]<CBool>)Runtime.LibraryGetExport(_libraryHandle, "sapp_keyboard_shown");
        _virtualTable.sapp_show_keyboard = (delegate* unmanaged[Cdecl]<CBool, void>)Runtime.LibraryGetExport(_libraryHandle, "sapp_show_keyboard");
        _virtualTable.sapp_dpi_scale = (delegate* unmanaged[Cdecl]<float>)Runtime.LibraryGetExport(_libraryHandle, "sapp_dpi_scale");
        _virtualTable.sapp_high_dpi = (delegate* unmanaged[Cdecl]<CBool>)Runtime.LibraryGetExport(_libraryHandle, "sapp_high_dpi");
        _virtualTable.sapp_sample_count = (delegate* unmanaged[Cdecl]<int>)Runtime.LibraryGetExport(_libraryHandle, "sapp_sample_count");
        _virtualTable.sapp_depth_format = (delegate* unmanaged[Cdecl]<int>)Runtime.LibraryGetExport(_libraryHandle, "sapp_depth_format");
        _virtualTable.sapp_color_format = (delegate* unmanaged[Cdecl]<int>)Runtime.LibraryGetExport(_libraryHandle, "sapp_color_format");
        _virtualTable.sapp_heightf = (delegate* unmanaged[Cdecl]<float>)Runtime.LibraryGetExport(_libraryHandle, "sapp_heightf");
        _virtualTable.sapp_height = (delegate* unmanaged[Cdecl]<int>)Runtime.LibraryGetExport(_libraryHandle, "sapp_height");
        _virtualTable.sapp_widthf = (delegate* unmanaged[Cdecl]<float>)Runtime.LibraryGetExport(_libraryHandle, "sapp_widthf");
        _virtualTable.sapp_width = (delegate* unmanaged[Cdecl]<int>)Runtime.LibraryGetExport(_libraryHandle, "sapp_width");
        _virtualTable.sapp_isvalid = (delegate* unmanaged[Cdecl]<CBool>)Runtime.LibraryGetExport(_libraryHandle, "sapp_isvalid");
        _virtualTable.sokol_main = (delegate* unmanaged[Cdecl]<int, CString*, sapp_desc>)Runtime.LibraryGetExport(_libraryHandle, "sokol_main");
        #endregion

        #region "Variables"

        #endregion
    }

    private static void _UnloadVirtualTable()
    {
        #region "Functions"

        _virtualTable.sapp_android_get_native_activity = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_wgpu_get_depth_stencil_view = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_wgpu_get_resolve_view = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_wgpu_get_render_view = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_wgpu_get_device = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_win32_get_hwnd = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_d3d11_get_depth_stencil_view = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_d3d11_get_render_target_view = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_d3d11_get_swap_chain = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_d3d11_get_device_context = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_d3d11_get_device = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_ios_get_window = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_macos_get_window = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_metal_get_drawable = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_metal_get_renderpass_descriptor = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_metal_get_device = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_html5_fetch_dropped_file = (delegate* unmanaged[Cdecl]<sapp_html5_fetch_request*, void>)IntPtr.Zero;
        _virtualTable.sapp_html5_get_dropped_file_size = (delegate* unmanaged[Cdecl]<int, uint>)IntPtr.Zero;
        _virtualTable.sapp_html5_ask_leave_site = (delegate* unmanaged[Cdecl]<CBool, void>)IntPtr.Zero;
        _virtualTable.sapp_gles2 = (delegate* unmanaged[Cdecl]<CBool>)IntPtr.Zero;
        _virtualTable.sapp_run = (delegate* unmanaged[Cdecl]<sapp_desc*, void>)IntPtr.Zero;
        _virtualTable.sapp_get_dropped_file_path = (delegate* unmanaged[Cdecl]<int, CString>)IntPtr.Zero;
        _virtualTable.sapp_get_num_dropped_files = (delegate* unmanaged[Cdecl]<int>)IntPtr.Zero;
        _virtualTable.sapp_set_icon = (delegate* unmanaged[Cdecl]<sapp_icon_desc*, void>)IntPtr.Zero;
        _virtualTable.sapp_set_window_title = (delegate* unmanaged[Cdecl]<CString, void>)IntPtr.Zero;
        _virtualTable.sapp_get_clipboard_string = (delegate* unmanaged[Cdecl]<CString>)IntPtr.Zero;
        _virtualTable.sapp_set_clipboard_string = (delegate* unmanaged[Cdecl]<CString, void>)IntPtr.Zero;
        _virtualTable.sapp_frame_count = (delegate* unmanaged[Cdecl]<ulong>)IntPtr.Zero;
        _virtualTable.sapp_consume_event = (delegate* unmanaged[Cdecl]<void>)IntPtr.Zero;
        _virtualTable.sapp_quit = (delegate* unmanaged[Cdecl]<void>)IntPtr.Zero;
        _virtualTable.sapp_cancel_quit = (delegate* unmanaged[Cdecl]<void>)IntPtr.Zero;
        _virtualTable.sapp_request_quit = (delegate* unmanaged[Cdecl]<void>)IntPtr.Zero;
        _virtualTable.sapp_query_desc = (delegate* unmanaged[Cdecl]<sapp_desc>)IntPtr.Zero;
        _virtualTable.sapp_userdata = (delegate* unmanaged[Cdecl]<void*>)IntPtr.Zero;
        _virtualTable.sapp_mouse_locked = (delegate* unmanaged[Cdecl]<CBool>)IntPtr.Zero;
        _virtualTable.sapp_lock_mouse = (delegate* unmanaged[Cdecl]<CBool, void>)IntPtr.Zero;
        _virtualTable.sapp_mouse_shown = (delegate* unmanaged[Cdecl]<CBool>)IntPtr.Zero;
        _virtualTable.sapp_show_mouse = (delegate* unmanaged[Cdecl]<CBool, void>)IntPtr.Zero;
        _virtualTable.sapp_toggle_fullscreen = (delegate* unmanaged[Cdecl]<void>)IntPtr.Zero;
        _virtualTable.sapp_is_fullscreen = (delegate* unmanaged[Cdecl]<CBool>)IntPtr.Zero;
        _virtualTable.sapp_keyboard_shown = (delegate* unmanaged[Cdecl]<CBool>)IntPtr.Zero;
        _virtualTable.sapp_show_keyboard = (delegate* unmanaged[Cdecl]<CBool, void>)IntPtr.Zero;
        _virtualTable.sapp_dpi_scale = (delegate* unmanaged[Cdecl]<float>)IntPtr.Zero;
        _virtualTable.sapp_high_dpi = (delegate* unmanaged[Cdecl]<CBool>)IntPtr.Zero;
        _virtualTable.sapp_sample_count = (delegate* unmanaged[Cdecl]<int>)IntPtr.Zero;
        _virtualTable.sapp_depth_format = (delegate* unmanaged[Cdecl]<int>)IntPtr.Zero;
        _virtualTable.sapp_color_format = (delegate* unmanaged[Cdecl]<int>)IntPtr.Zero;
        _virtualTable.sapp_heightf = (delegate* unmanaged[Cdecl]<float>)IntPtr.Zero;
        _virtualTable.sapp_height = (delegate* unmanaged[Cdecl]<int>)IntPtr.Zero;
        _virtualTable.sapp_widthf = (delegate* unmanaged[Cdecl]<float>)IntPtr.Zero;
        _virtualTable.sapp_width = (delegate* unmanaged[Cdecl]<int>)IntPtr.Zero;
        _virtualTable.sapp_isvalid = (delegate* unmanaged[Cdecl]<CBool>)IntPtr.Zero;
        _virtualTable.sokol_main = (delegate* unmanaged[Cdecl]<int, CString*, sapp_desc>)IntPtr.Zero;

        #endregion

        #region "Variables"



        #endregion
    }

    // The virtual table represents a list of pointers to functions or variables which are resolved in a late manner.
    //	This allows for flexibility in swapping implementations at runtime.
    //	You can think of it in traditional OOP terms in C# as the locations of the virtual methods and/or properties of an object.
    public struct _VirtualTable
    {
        #region "Function Pointers"
        // These pointers hold the locations in the native library where functions are located at runtime.
        // See: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers

        public delegate* unmanaged[Cdecl]<void*> sapp_android_get_native_activity;
        public delegate* unmanaged[Cdecl]<void*> sapp_wgpu_get_depth_stencil_view;
        public delegate* unmanaged[Cdecl]<void*> sapp_wgpu_get_resolve_view;
        public delegate* unmanaged[Cdecl]<void*> sapp_wgpu_get_render_view;
        public delegate* unmanaged[Cdecl]<void*> sapp_wgpu_get_device;
        public delegate* unmanaged[Cdecl]<void*> sapp_win32_get_hwnd;
        public delegate* unmanaged[Cdecl]<void*> sapp_d3d11_get_depth_stencil_view;
        public delegate* unmanaged[Cdecl]<void*> sapp_d3d11_get_render_target_view;
        public delegate* unmanaged[Cdecl]<void*> sapp_d3d11_get_swap_chain;
        public delegate* unmanaged[Cdecl]<void*> sapp_d3d11_get_device_context;
        public delegate* unmanaged[Cdecl]<void*> sapp_d3d11_get_device;
        public delegate* unmanaged[Cdecl]<void*> sapp_ios_get_window;
        public delegate* unmanaged[Cdecl]<void*> sapp_macos_get_window;
        public delegate* unmanaged[Cdecl]<void*> sapp_metal_get_drawable;
        public delegate* unmanaged[Cdecl]<void*> sapp_metal_get_renderpass_descriptor;
        public delegate* unmanaged[Cdecl]<void*> sapp_metal_get_device;
        public delegate* unmanaged[Cdecl]<sapp_html5_fetch_request*, void> sapp_html5_fetch_dropped_file;
        public delegate* unmanaged[Cdecl]<int, uint> sapp_html5_get_dropped_file_size;
        public delegate* unmanaged[Cdecl]<CBool, void> sapp_html5_ask_leave_site;
        public delegate* unmanaged[Cdecl]<CBool> sapp_gles2;
        public delegate* unmanaged[Cdecl]<sapp_desc*, void> sapp_run;
        public delegate* unmanaged[Cdecl]<int, CString> sapp_get_dropped_file_path;
        public delegate* unmanaged[Cdecl]<int> sapp_get_num_dropped_files;
        public delegate* unmanaged[Cdecl]<sapp_icon_desc*, void> sapp_set_icon;
        public delegate* unmanaged[Cdecl]<CString, void> sapp_set_window_title;
        public delegate* unmanaged[Cdecl]<CString> sapp_get_clipboard_string;
        public delegate* unmanaged[Cdecl]<CString, void> sapp_set_clipboard_string;
        public delegate* unmanaged[Cdecl]<ulong> sapp_frame_count;
        public delegate* unmanaged[Cdecl]<void> sapp_consume_event;
        public delegate* unmanaged[Cdecl]<void> sapp_quit;
        public delegate* unmanaged[Cdecl]<void> sapp_cancel_quit;
        public delegate* unmanaged[Cdecl]<void> sapp_request_quit;
        public delegate* unmanaged[Cdecl]<sapp_desc> sapp_query_desc;
        public delegate* unmanaged[Cdecl]<void*> sapp_userdata;
        public delegate* unmanaged[Cdecl]<CBool> sapp_mouse_locked;
        public delegate* unmanaged[Cdecl]<CBool, void> sapp_lock_mouse;
        public delegate* unmanaged[Cdecl]<CBool> sapp_mouse_shown;
        public delegate* unmanaged[Cdecl]<CBool, void> sapp_show_mouse;
        public delegate* unmanaged[Cdecl]<void> sapp_toggle_fullscreen;
        public delegate* unmanaged[Cdecl]<CBool> sapp_is_fullscreen;
        public delegate* unmanaged[Cdecl]<CBool> sapp_keyboard_shown;
        public delegate* unmanaged[Cdecl]<CBool, void> sapp_show_keyboard;
        public delegate* unmanaged[Cdecl]<float> sapp_dpi_scale;
        public delegate* unmanaged[Cdecl]<CBool> sapp_high_dpi;
        public delegate* unmanaged[Cdecl]<int> sapp_sample_count;
        public delegate* unmanaged[Cdecl]<int> sapp_depth_format;
        public delegate* unmanaged[Cdecl]<int> sapp_color_format;
        public delegate* unmanaged[Cdecl]<float> sapp_heightf;
        public delegate* unmanaged[Cdecl]<int> sapp_height;
        public delegate* unmanaged[Cdecl]<float> sapp_widthf;
        public delegate* unmanaged[Cdecl]<int> sapp_width;
        public delegate* unmanaged[Cdecl]<CBool> sapp_isvalid;
        public delegate* unmanaged[Cdecl]<int, CString*, sapp_desc> sokol_main;

        #endregion

        #region "Variables"
        // These pointers hold the locations in the native library where global variables are located at runtime.
        //	The value pointed by these pointers are updated by reading/writing memory.



        #endregion
    }

    private static _VirtualTable _virtualTable;
}
