
//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using C2CS;

#nullable enable
#pragma warning disable 1591

public static unsafe partial class sokol_audio
{
    private const string LibraryName = "sokol";

    // Function @ sokol_audio.h:445:26
    [DllImport("sokol")]
    public static extern int saudio_push(float* frames, int num_frames);

    // Function @ sokol_audio.h:443:26
    [DllImport("sokol")]
    public static extern int saudio_expect();

    // Function @ sokol_audio.h:441:26
    [DllImport("sokol")]
    public static extern int saudio_channels();

    // Function @ sokol_audio.h:439:26
    [DllImport("sokol")]
    public static extern int saudio_buffer_frames();

    // Function @ sokol_audio.h:437:26
    [DllImport("sokol")]
    public static extern int saudio_sample_rate();

    // Function @ sokol_audio.h:435:34
    [DllImport("sokol")]
    public static extern saudio_desc saudio_query_desc();

    // Function @ sokol_audio.h:433:28
    [DllImport("sokol")]
    public static extern void* saudio_userdata();

    // Function @ sokol_audio.h:431:27
    [DllImport("sokol")]
    public static extern CBool saudio_isvalid();

    // Function @ sokol_audio.h:429:27
    [DllImport("sokol")]
    public static extern void saudio_shutdown();

    // Function @ sokol_audio.h:427:27
    [DllImport("sokol")]
    public static extern void saudio_setup(saudio_desc* desc);

    // FunctionPointer @ sokol_audio.h:422:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_AUDIO_FloatPtr_Int_Int_VoidPtr_Void
    {
        public delegate* unmanaged<float*, int, int, void*, void> Pointer;
    }

    // FunctionPointer @ sokol_audio.h:421:12
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_SOKOL_AUDIO_FloatPtr_Int_Int_Void
    {
        public delegate* unmanaged<float*, int, int, void> Pointer;
    }

    // Struct @ sokol_audio.h:424:3
    [StructLayout(LayoutKind.Explicit, Size = 48, Pack = 8)]
    public struct saudio_desc
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int sample_rate;

        [FieldOffset(4)] // size = 4, padding = 0
        public int num_channels;

        [FieldOffset(8)] // size = 4, padding = 0
        public int buffer_frames;

        [FieldOffset(12)] // size = 4, padding = 0
        public int packet_frames;

        [FieldOffset(16)] // size = 4, padding = 4
        public int num_packets;

        [FieldOffset(24)] // size = 8, padding = 0
        public FnPtr_SOKOL_AUDIO_FloatPtr_Int_Int_Void stream_cb;

        [FieldOffset(32)] // size = 8, padding = 0
        public FnPtr_SOKOL_AUDIO_FloatPtr_Int_Int_VoidPtr_Void stream_userdata_cb;

        [FieldOffset(40)] // size = 8, padding = 0
        public void* user_data;
    }
}
