
//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs (v1.1.0.0)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using C2CS;

#nullable enable
#pragma warning disable 1591

public static unsafe partial class sokol_time
{
    private const string LibraryName = "sokol";

    // Function @ sokol_time.h:135:28 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern double stm_ns(ulong ticks);

    // Function @ sokol_time.h:134:28 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern double stm_us(ulong ticks);

    // Function @ sokol_time.h:133:28 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern double stm_ms(ulong ticks);

    // Function @ sokol_time.h:132:28 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern double stm_sec(ulong ticks);

    // Function @ sokol_time.h:131:30 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern ulong stm_round_to_common_refresh_rate(ulong frame_ticks);

    // Function @ sokol_time.h:130:30 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern ulong stm_laptime(ulong* last_time);

    // Function @ sokol_time.h:129:30 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern ulong stm_since(ulong start_ticks);

    // Function @ sokol_time.h:128:30 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern ulong stm_diff(ulong new_ticks, ulong old_ticks);

    // Function @ sokol_time.h:127:30 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern ulong stm_now();

    // Function @ sokol_time.h:126:26 (/mnt/c/Users/lithi/Programming/sokol-cs/ext/sokol/sokol_time.h)
    [DllImport(LibraryName)]
    public static extern void stm_setup();
}
