// Copyright (c) Lucas Girouard-Stranks. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Runtime.InteropServices;

namespace Sokol.Graphics
{
    /// <summary>
    ///     The parameters that describe the output destination for pixels generated by a render <see cref="Pass" />.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         <see cref="PassAttachmentDescriptor" /> is used to configure an individual render target
    ///         <see cref="Image" /> that the <see cref="Pass" /> can write into.
    ///     </para>
    ///     <para>
    ///         Use standard struct allocation and initialization techniques to create
    ///         a <see cref="PassAttachmentDescriptor" />.
    ///     </para>
    ///     <para>
    ///         The <see cref="Image" /> property must be set and it must be a render target
    ///         (see <see cref="ImageDescriptor.IsRenderTarget" />). The set <see cref="Image" /> for all
    ///         attachments of a rendering <see cref="Pass" /> must have the same dimensions and the same sample count.
    ///         In addition, the set <see cref="Image" /> for all color attachments must have the same
    ///         <see cref="PixelFormat" />. The <see cref="Level"/> and <see cref="Slice"/> properties specify the
    ///         mipmap level and the slice, of the <see cref="Image" />, respectively.
    ///     </para>
    ///     <para>
    ///         <see cref="PassAttachmentDescriptor" /> is blittable to the C `sg_attachment_desc` struct found in
    ///         `sokol_gfx`.
    ///     </para>
    /// </remarks>
    [StructLayout(LayoutKind.Explicit, Size = 12, Pack = 4)]
    public struct PassAttachmentDescriptor
    {
        /// <summary>
        ///     The render target <see cref="Image" />. Must be set. Must be a render target.
        /// </summary>
        [FieldOffset(0)]
        public Image Image;

        /// <summary>
        ///     The mipmap level of the <see cref="Image" /> used for rendering to the attachment.
        /// </summary>
        [FieldOffset(4)]
        public int Level;

        /// <summary>
        ///     The slice of the <see cref="Image" /> used for rendering to the attachment.
        /// </summary>
        [FieldOffset(8)]
        public int Slice;
    }
}
