name: 'Upate sokol_app libs'

on: 
  repository_dispatch:
    types: [sokol_app-bin]

jobs:

  commit-job:
    name: 'Commit sokol_app binaries'
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: 'Get latest release meta data'
      id: latest-release-meta
      run: echo "::set-output name=tag_name::$(curl --silent "https://api.github.com/repos/lithiumtoast/sokol_app-bin/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"

    - name: 'Download latest release: Windows'
      run: |
        wget "https://github.com/lithiumtoast/sokol_app-bin/releases/latest/download/win-x64.zip"

    - name: 'Download latest release: macOS'
      run: |
        wget "https://github.com/lithiumtoast/sokol_app-bin/releases/latest/download/osx-x64.zip"

    - name: 'Download latest release: Linux'
      run: |
        wget "https://github.com/lithiumtoast/sokol_app-bin/releases/latest/download/linux-x64.zip"

    - name: 'Organize downloaded files'
      run: |
        mkdir -p lib/libsokol_app/win-x64
        unzip win-x64.zip -d lib/libsokol_app
        rm win-x64.zip
        mkdir -p lib/libsokol_app/osx-x64
        unzip osx-x64.zip -d lib/libsokol_app
        rm osx-x64.zip
        mkdir -p lib/libsokol_app/linux-x64
        unzip linux-x64.zip -d lib/libsokol_app
        rm linux-x64.zip

    - name: 'Create pull request'
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: 'Update `sokol_app` binaries to `${{ steps.latest-release-meta.outputs.tag_name }}`'
        title: 'build: Update `sokol_app` binaries to `${{ steps.latest-release-meta.outputs.tag_name }}`'
        body: "A build for `sokol_app` was released: [`${{ steps.latest-release-meta.outputs.tag_name }}`](https://github.com/lithiumtoast/sokol_app-bin/releases/latest).\nThis updates the `sokol_app` binaries for this repository."
        branch: sokol_app-bin
